draw_config:
  key_h: 70.0
  combo_w: 25.0
  combo_h: 60.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 5.0
  inner_pad_h: 5.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 10.0
  arc_scale: 1.0
  append_colon_to_layer_header: false
  small_pad: 7.0
  svg_style: |
    /* reusable color variables. palette taken from https://github.com/rebelot/kanagawa.nvim */
    :root {
        --background-color: #1F1F28;
        --foreground-color: #E6C384;
        --held-color: #98BB6C;
        --shifted-color: #DCD7BA;
        --layer-color: #C34043;
        --combo-color: #938AA9;
        --keycap-color: #727169;
    }

    svg {
        background-color: var(--background-color);
    }

    rect {
        fill: var(--background-color);
        stroke: var(--keycap-color);
        stroke-width: 2;
    }

    rect.combo {
        stroke: var(--combo-color);
    }

    .held, .hold {
        fill: var(--held-color);
    }

    text {
        font-family: JetBrainsMono NFM,SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 14px;
        font-weight: bold;
        text-anchor: middle;
        dominant-baseline: middle;
        font-weight: bold;
        fill: var(--foreground-color);
    }

    text.label {
        font-size: 24px;
        text-anchor: start;
        fill: var(--layer-color);
        paint-order: stroke;
    }

    text.hold, text.shifted {
        font-size: 12px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
        fill: var(--shifted-color);
    }

    path.combo {
        stroke-width: 2;
        stroke: var(--combo-color);
        fill: none;
    }
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map: {}
  zmk_combos:
    combo_qu: 
       'k': {t: 'Qu', h: 'Q'}
    combo_th: 
       'k': {t: 'Th'}
    combo_ch: 
       'k': {t: 'Ch'}
    combo_sh: 
       'k': {t: 'Sh'}
    combo_wh: 
       'k': {t: 'Wh'}
    combo_gh: 
       'k': {t: 'Gh'}
    combo_ph: 
       'k': {t: 'Ph'}
  sticky_label: sticky
  trans_legend:
    t: ▽
    type: trans
  zmk_keycode_map:
    # For true 'bold', prefer JetBrainsMono natively supported glyphs: https://www.jetbrains.com/lp/mono/
    EXCLAMATION: '!'
    EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: '='
    PLUS: +
    MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    SLASH: /
    FSLH: /
    QUESTION: '?'
    QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PERIOD: .
    DOT: .
    GREATER_THAN: '>'
    GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    GRAVE: '`'
    TILDE: '~'
    NON_US_HASH: '#'
    NUHS: '#'
    TILDE2: '~'
    DEL: '⌦'
    BSPC: '⌫'
    RET: '⏎'
    SPACE: '‿'
    TAB: '⭾'
    LSHIFT: 'Shift'
    RSHIFT: 'Shift'
    LALT: 'Alt'
    RALT: 'Alt'
    LCTRL: 'Ctrl'
    RCTRL: 'Ctrl'
    LMETA: 'Meta'
    RMETA: 'Meta'
